# Generated by Django 5.0.7 on 2024-09-21 15:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myquiz', '0002_remove_quiz_academic_session'),
    ]

    operations = [
        migrations.RenameField(
            model_name='quiz',
            old_name='end_time',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='quiz',
            old_name='start_time',
            new_name='start_date',
        ),
    ]
