# Generated by Django 5.0.7 on 2024-09-21 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myquiz', '0003_rename_end_time_quiz_end_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='quiz_images/%Y/%m/%d/'),
        ),
        migrations.AlterField(
            model_name='questionbank',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='question_bank_images/%Y/%m/%d/'),
        ),
    ]
