# Generated by Django 5.0.7 on 2024-10-04 07:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myquiz', '0007_alter_studentanswer_selected_option'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='option_5',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='question',
            name='option_6',
            field=models.CharField(default='', max_length=200),
        ),
    ]
