# Generated by Django 5.0.7 on 2024-12-01 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myquiz', '0008_question_option_5_question_option_6'),
    ]

    operations = [
        migrations.AddField(
            model_name='quiz',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
