# Generated by Django 5.0.7 on 2025-01-06 21:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myquiz', '0009_quiz_duration'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quiz',
            name='duration',
        ),
    ]
