# Generated by Django 5.0.7 on 2024-10-10 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notification", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="notification",
            old_name="created_at",
            new_name="timestamp",
        ),
        migrations.AddField(
            model_name="notification",
            name="is_read",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="notification",
            name="icon",
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
