# Generated by Django 5.0.7 on 2024-08-24 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='academicsession',
            name='next_session_begins',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='term',
            name='next_term_begins',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='school',
            name='address',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='school',
            name='logo',
            field=models.URLField(default=''),
        ),
    ]
