# Generated by Django 5.0.7 on 2024-08-27 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='category',
            field=models.CharField(blank=True, choices=[('ART', 'Art Class'), ('SCIENCE', 'Science Class'), ('COMMERCIAL', 'Commercial Class')], max_length=12, null=True),
        ),
    ]
