# Generated by Django 5.0.7 on 2024-09-01 10:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gmeetclass',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'owner'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gmeets', to=settings.AUTH_USER_MODEL),
        ),
    ]
