# Generated by Django 5.0.7 on 2024-09-03 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_alter_gmeetclass_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='name',
            field=models.CharField(choices=[('BASIC1', 'Basic 1'), ('Basic2', 'Basic 2'), ('Basic3', 'Basic 3'), ('Basic4', 'Basic 4'), ('Basic5', 'Basic 5'), ('Basic6', 'Basic 6'), ('KG1', 'Kindergarten 1'), ('KG2', 'Kindergarten 2'), ('KG3', 'Kindergarten 3'), ('PRY1', 'Primary 1'), ('PRY2', 'Primary 2'), ('PRY3', 'Primary 3'), ('PRY4', 'Primary 4'), ('PRY5', 'Primary 5'), ('PRY6', 'Primary 6'), ('JS1', 'Junior Secondary 1'), ('JS2', 'Junior Secondary 2'), ('JS3', 'Junior Secondary 3'), ('SS1', 'Senior Secondary 1'), ('SS2', 'Senior Secondary 2'), ('SS3', 'Senior Secondary 3')], max_length=6),
        ),
    ]
