# Generated by Django 5.0.7 on 2024-08-24 21:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_academicsession_next_session_begins_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmeetclass',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='gmeetclass',
            name='description',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
