# Generated by Django 5.0.7 on 2024-08-25 23:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_schoolcategory_remove_student_gender_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schoolclass',
            name='class_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
    ]
