# Generated by Django 5.0.7 on 2024-08-29 14:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_schoolclass_division_delete_division'),
    ]

    operations = [
        migrations.AddField(
            model_name='continuousassessment',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='assessment/%Y/%m/%d/'),
        ),
        migrations.AddField(
            model_name='teacher',
            name='department',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='subject',
            name='teacher',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='main.teacher'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'A user with that username already exists.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
