# Generated by Django 5.0.7 on 2024-09-07 15:40

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_gmeetclass_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='gmeetclass',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='gmeetclass',
            name='created_by',
            field=models.ForeignKey(blank=True, limit_choices_to={'role__in': ['teacher', 'admin', 'owner']}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gmeets', to=settings.AUTH_USER_MODEL),
        ),
    ]
