# Generated by Django 5.0.7 on 2024-08-26 16:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_schoolclass_class_teacher'),
        ('main', '0004_classnote_for_class'),
    ]

    operations = [
    ]
