# Generated by Django 5.0.7 on 2024-08-27 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_alter_schoolclass_class_teacher'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='SchoolSettings',
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='category',
            field=models.CharField(blank=True, choices=[('A', 'Art Class'), ('S', 'Science Class'), ('C', 'Commercial Class')], max_length=1, null=True),
        ),
    ]
