# Generated by Django 5.0.7 on 2024-09-08 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_gmeetclass_title_alter_gmeetclass_created_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='title',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
