# Generated by Django 5.0.7 on 2024-08-26 17:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_merge_20240826_1655'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Settings',
            new_name='SchoolSettings',
        ),
    ]
