# Generated by Django 5.0.7 on 2024-09-12 04:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_lessonplan_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gmeetclass',
            name='end_time',
        ),
        migrations.AddField(
            model_name='gmeetclass',
            name='duration',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
