# Generated by Django 5.0.7 on 2024-08-31 07:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_alter_user_email_alter_user_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='school',
            field=models.ForeignKey(default=160, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='main.school'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(blank=True, error_messages={'unique': 'An Admin, Teacher or Student with that email already exists.'}, max_length=254, unique=True, verbose_name='email address'),
        ),
    ]
