# Generated by Django 5.0.7 on 2024-09-16 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_rename_academic_year_student_session_admitted_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='academicsession',
            options={'ordering': ['-is_current']},
        ),
        migrations.AlterUniqueTogether(
            name='academicsession',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='category',
            field=models.CharField(blank=True, choices=[('ART', 'Art Class'), ('SCIENCE', 'Science Class'), ('PRIMARY', 'Primary Classes'), ('JUNIOR SEC', 'Junior Secondary Classes'), ('SCIENCE_TECH', 'Science and Technology Class'), ('COMMERCIAL', 'Commercial Class')], max_length=12, null=True),
        ),
    ]
