# Generated by Django 5.0.7 on 2024-08-31 07:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_student_school_alter_user_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='owner',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='school', to=settings.AUTH_USER_MODEL),
        ),
    ]
