# Generated by Django 5.0.7 on 2024-09-21 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_term_is_current'),
    ]

    operations = [
        migrations.AlterField(
            model_name='term',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='term',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
