# Generated by Django 5.0.7 on 2024-10-04 07:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_classnote_uploaded_by_alter_lessonplan_uploaded_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonplan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='lessonplan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='category',
            field=models.CharField(blank=True, choices=[('ART', 'Art Class'), ('SCIENCE', 'Science Class'), ('PRIMARY', 'Primary Classes'), ('JUNIOR SEC', 'Junior Secondary Classes'), ('SCIENCE_TECH', 'Science and Technology Class'), ('COMMERCIAL', 'Commercial Class')], default='', max_length=12, null=True),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='division',
            field=models.CharField(blank=True, choices=[('A', 'A'), ('B', 'B'), ('C', 'C'), ('D', 'D'), ('E', 'E'), ('F', 'F'), ('G', 'G'), ('H', 'H'), ('I', 'I'), ('J', 'J'), ('K', 'K'), ('L', 'L'), ('M', 'M'), ('N', 'N'), ('O', 'O'), ('P', 'P'), ('Q', 'Q'), ('R', 'R'), ('S', 'S'), ('T', 'T'), ('U', 'U'), ('V', 'V'), ('W', 'W'), ('X', 'X'), ('Y', 'Y'), ('Z', 'Z')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='schoolclass',
            name='name',
            field=models.CharField(choices=[('Basic1', 'Basic 1'), ('Basic2', 'Basic 2'), ('Basic3', 'Basic 3'), ('Basic4', 'Basic 4'), ('Basic5', 'Basic 5'), ('Basic6', 'Basic 6'), ('KG1', 'Kindergarten 1'), ('KG2', 'Kindergarten 2'), ('KG3', 'Kindergarten 3'), ('PRY1', 'Primary 1'), ('PRY2', 'Primary 2'), ('PRY3', 'Primary 3'), ('PRY4', 'Primary 4'), ('PRY5', 'Primary 5'), ('PRY6', 'Primary 6'), ('JS1', 'Junior Secondary 1'), ('JS2', 'Junior Secondary 2'), ('JS3', 'Junior Secondary 3'), ('SS1', 'Senior Secondary 1'), ('SS2', 'Senior Secondary 2'), ('SS3', 'Senior Secondary 3')], max_length=6),
        ),
        migrations.AlterUniqueTogether(
            name='academicsession',
            unique_together={('school', 'name')},
        ),
    ]
