# Generated by Django 5.0.7 on 2025-01-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0015_gmeetclass_school_lessonplan_school_school_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='about',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='school',
            name='motto',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='school',
            name='website',
            field=models.URLField(blank=True, null=True),
        ),
    ]
